flowchart LR
  Main --> Missions
  Missions --> Autocorrect
  Missions --> Motion
  Missions --> LineFollow
  Missions --> Attachment
  Motion --> Hardware
  LineFollow --> Hardware
  Attachment --> Hardware
  Hardware --> Sensors
  Hardware --> Motors
  Sensors --> ControlLogic
  ControlLogic --> Missions
