
PORT_LEFT_MOTOR='B';PORT_RIGHT_MOTOR='C';PORT_ARM_MOTOR='A'
PORT_COLOR_SENSOR='D';PORT_DISTANCE_SENSOR='E';PORT_FORCE_SENSOR='F'
USE_GYRO=True;USE_COLOR_SENSOR=True;USE_DISTANCE_SENSOR=True;USE_FORCE_SENSOR=False
WHEEL_CIRCUMFERENCE_CM=17.6;TURN_FACTOR_DEG_PER_DEG=0.95
LINE_TARGET=50;LINE_KP=0.35;WALL_APPROACH_CM=8.0
DEFAULT_SPEED=35;SLOW_SPEED=20;STEP_TIMEOUT_S=4.0;MAX_RETRIES=1;VERBOSE=True
